version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
  posterr-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    tty: true
    stdin_open: true
    depends_on:
      - postgres
