version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  posterr-api:
    restart: always
    image: node:16-alpine
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    tty: true
    stdin_open: true
    depends_on:
      - postgres
